In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews=['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']
sentiments=np.array([1,1,1,1,1,0,0,0,0,0])

In [11]:
v_size=30
encoded_review=[one_hot(r,v_size) for r in reviews]
encoded_review

[[1, 6],
 [26, 19],
 [23, 17],
 [7, 9, 10],
 [19, 26, 20],
 [9, 6],
 [7, 26, 7],
 [19, 20],
 [19, 22],
 [6, 17]]

In [15]:
max_sentence_len=3
padded_reviews=pad_sequences(encoded_review,max_sentence_len,padding='post')
padded_reviews

array([[ 1,  6,  0],
       [26, 19,  0],
       [23, 17,  0],
       [ 7,  9, 10],
       [19, 26, 20],
       [ 9,  6,  0],
       [ 7, 26,  7],
       [19, 20,  0],
       [19, 22,  0],
       [ 6, 17,  0]])

In [19]:
embedding_size=4

model=Sequential()
model.add(Embedding(v_size,embedding_size,input_length=max_sentence_len,name='first_embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
x=padded_reviews
y=sentiments

In [25]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ first_embedding (Embedding)     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.fit(x,y,epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.7000 - loss: 0.6904
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.7000 - loss: 0.6897
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7000 - loss: 0.6891
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.7000 - loss: 0.6884
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.7000 - loss: 0.6877
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7000 - loss: 0.6870
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.7000 - loss: 0.6863
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7000 - loss: 0.6856
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.7000 - loss: 0.6849
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.7000 - loss: 0.6842
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.7000 - loss: 0.6835
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.7000 - loss:

In [29]:
model.evaluate(x,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 515ms/step - accuracy: 0.9000 - loss: 0.6522


[0.6522175073623657, 0.8999999761581421]

In [47]:
weights=model.get_layer('first_embedding').get_weights()[0]

In [49]:
weights[1]

array([-0.09058272, -0.03316097,  0.00831165, -0.06105186], dtype=float32)

In [51]:
weights[26]

array([-0.00763721, -0.07727487, -0.03009187, -0.03585624], dtype=float32)