In [1]:
import tensorflow as tf

In [2]:
sales=[21,22,31,-108,32,34,-1,31]

In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(sales)

In [7]:
for i in tf_dataset.as_numpy_iterator():
  print(i)

21
22
31
-108
32
34
-1
31


In [8]:
for j in tf_dataset.take(3):
  print(j)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [10]:
tf_dataset=tf_dataset.filter(lambda x:x>0)

In [11]:
for i in tf_dataset.as_numpy_iterator():
  print(i)

21
22
31
32
34
31


In [12]:
tf_datas=tf_dataset.map(lambda x:x*90)

In [13]:
for j in tf_datas.as_numpy_iterator():
  print(j)

1890
1980
2790
2880
3060
2790


In [16]:
for s in tf_datas.batch(2):
  print(s.numpy())

[1890 1980]
[2790 2880]
[3060 2790]


In [19]:
tf_new=tf.data.Dataset.from_tensor_slices(sales)

tf_new=tf_new.filter(lambda x:x>0).map(lambda y:y*90).batch(3)

In [20]:
for i in tf_new.as_numpy_iterator():
  print(i)

[1890 1980 2790]
[2880 3060 2790]


In [22]:
import zipfile
zipp=zipfile.ZipFile("/content/F.zip")
zipp.extractall()

In [26]:
img_list=tf.data.Dataset.list_files("/content/flower_photos/*/*/*")

In [27]:
for img in img_list:
  print(img.numpy())

b'/content/flower_photos/flower_photos/roses/8983268106_dc913d17d8_m.jpg'
b'/content/flower_photos/flower_photos/dandelion/11768468623_9399b5111b_n.jpg'
b'/content/flower_photos/flower_photos/dandelion/18876985840_7531dc8e6a.jpg'
b'/content/flower_photos/flower_photos/sunflowers/20171662239_f69b6c12bd_n.jpg'
b'/content/flower_photos/flower_photos/sunflowers/9056495873_66e351b17c_n.jpg'
b'/content/flower_photos/flower_photos/dandelion/2478018280_1be353ca8c_m.jpg'
b'/content/flower_photos/flower_photos/sunflowers/4019748730_ee09b39a43.jpg'
b'/content/flower_photos/flower_photos/dandelion/18304194360_2a4a0be631_m.jpg'
b'/content/flower_photos/flower_photos/dandelion/315645471_dda66c6338_m.jpg'
b'/content/flower_photos/flower_photos/tulips/430785322_7ddef64c68_m.jpg'
b'/content/flower_photos/flower_photos/tulips/13542672763_20c3cb9272.jpg'
b'/content/flower_photos/flower_photos/tulips/12557176134_ecbf15885b.jpg'
b'/content/flower_photos/flower_photos/sunflowers/3568925290_faf7aec3a0.jpg'
b

In [29]:
img_count=len(img_list)

In [30]:
train_size=int(img_count*0.8)

In [60]:
train_ds=img_list.take(train_size)
test_ds=img_list.skip(train_size)

In [42]:
def get_y(img_path):
  import os
  y=tf.strings.split(img_path,os.path.sep)[-2]
  return y

In [61]:
def get_x(img_path):
  y=get_y(img_path)
  x=tf.io.read_file(img_path)
  x=tf.image.decode_jpeg(x)
  x=tf.image.resize(x,(224,224))
  return x,y

In [62]:
train_ds=train_ds.map(get_x)

In [63]:
for i,j in train_ds.take(3):
  print(i)
  print(j)

tf.Tensor(
[[[159.4289  174.06473 144.3278 ]
  [175.6451  185.06761 163.7634 ]
  [180.0051  192.39731 175.11287]
  ...
  [153.16519 154.2819  129.33548]
  [173.42542 173.03256 149.33008]
  [161.79662 161.40375 137.36804]]

 [[143.4257  163.34502 100.87819]
  [113.28795 136.32271  76.34981]
  [154.90657 170.83131 152.45886]
  ...
  [174.22198 170.72932 152.60782]
  [174.93524 171.93524 154.88103]
  [168.99146 166.06001 147.93498]]

 [[138.87787 159.06537  99.9088 ]
  [103.58386 137.58769  69.73183]
  [ 90.15147 122.49681  79.73247]
  ...
  [173.31601 168.44386 148.73276]
  [177.30188 175.26616 152.4696 ]
  [170.57336 168.55136 143.73822]]

 ...

 [[172.98495 182.94925 183.85042]
  [177.6623  186.77837 191.2159 ]
  [188.47034 197.27104 202.27711]
  ...
  [182.57417 185.8809  176.69978]
  [176.83942 178.8697  174.10188]
  [175.56995 176.59195 179.59265]]

 [[179.22958 188.22958 185.44963]
  [181.44    189.59178 191.13643]
  [194.98587 200.47858 203.47858]
  ...
  [171.04726 176.12761 168.

In [66]:
def scale(img,label):
  return img/255,label

In [67]:
train_ds=train_ds.map(scale)

In [68]:
for i,j in train_ds:
  print(i)
  print(j)


Streaming output truncated to the last 5000 lines.
  [0.8790191  0.9496073  0.98882306]]], shape=(224, 224, 3), dtype=float32)
tf.Tensor(b'roses', shape=(), dtype=string)
tf.Tensor(
[[[8.33503366e-01 6.80592239e-01 7.31632650e-01]
  [8.41556609e-01 6.63915575e-01 6.96208537e-01]
  [7.65376151e-01 5.62675059e-01 5.73289275e-01]
  ...
  [1.13382526e-01 7.66481906e-02 3.46641913e-02]
  [1.81071297e-03 1.76471006e-02 1.51759684e-02]
  [7.20300013e-04 4.26575840e-02 3.60150007e-04]]

 [[6.68107271e-01 2.65856355e-01 2.84153670e-01]
  [7.27270842e-01 3.06142479e-01 3.22499037e-01]
  [8.17236841e-01 3.84313732e-01 3.94507796e-01]
  ...
  [2.18996182e-01 1.80341318e-01 5.71126118e-02]
  [5.35210930e-02 6.50057942e-02 1.53260566e-02]
  [1.87578183e-02 5.80238737e-02 1.01742316e-02]]

 [[6.92216933e-01 1.18647434e-01 1.58903554e-01]
  [6.53991580e-01 4.86394316e-02 1.02460958e-01]
  [7.24349737e-01 5.81332371e-02 1.35804296e-01]
  ...
  [2.82722205e-01 2.38665134e-01 6.62654117e-02]
  [7.1828275